conquista/urls.py
from django.contrib import admin
from django.urls import path

from conquista import views

app_name = 'conquista'

urlpatterns = [
    path('', views.index, name="index"),
]

pais/urls.py
from django.contrib import admin
from django.urls import path

from pais import views

app_name = 'pais'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:id>', views.show, name="show"),
]

palavra_vida/urls.py
from django.contrib import admin
from django.urls import path

from palavra_vida import views

app_name = 'palavra_vida'

urlpatterns = [
    path('', views.index, name="index"),
    path('cadastra_motivacao/', views.cadastra_motivacao, name='cadastra_motivacao'),
]

projeto/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from projeto import views, settings

urlpatterns = [
    path('', views.index, name="index"),
    path('pais/', include('pais.urls')),
    path('conquista/', include('conquista.urls')),
    path('palavra_vida/', include('palavra_vida.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conquista/models.py
from django.db import models

# Create your models here.
class Conquista(models.Model):
    titulo = models.CharField(max_length=100, db_index= True, unique=True)
    descricao = models.TextField(default='')
    documento = models.FileField(upload_to='documentos/conquistas/', blank=True)
    localidade = models.CharField(max_length=250, default='')
    link = models.CharField(max_length=150, blank=True)
    data = models.DateField(default='')

    class Meta:
        db_table = 'conquista'
        ordering = ('data',)

    def __str__(self):
        return self.titulo;

    def definir_mes(self):
        meses = ['JANEIRO', 'FEVEREIRO', 'MARÇO', 'ABRIL', 'MAIO', 'JUNHO', 'JULHO', 'AGOSTO', 'SETEMBRO', 'OUTUBRO', 'NOVEMBRO', 'DEZEMBRO']
        return meses[self.data.month-1];

missao/models.py
from django.db import models

# Create your models here.

pais/models.py
from django.db import models

class Continente(models.Model):
    nome = models.CharField(max_length=100, db_index=True, unique=True)

    class Meta:
        db_table = 'continente'
        ordering = ('nome',)

    def __str__(self):
        return self.nome;

class Idioma(models.Model):
    nome = models.CharField(max_length=100, db_index=True, unique=True)

    class Meta:
        db_table = 'idioma'
        ordering = ('nome',)

    def __str__(self):
        return self.nome;

class Religiao(models.Model):
    nome = models.CharField(max_length=100, db_index=True, unique=True)
    descricao = models.TextField(blank=True)

    class Meta:
        db_table = 'religiao'
        ordering = ('nome',)

    def __str__(self):
        return self.nome;

class Perseguicao(models.Model):
    tipo = models.TextField(blank=True)
    descricao = models.TextField(blank=True)

    class Meta:
        db_table = 'perseguicao'

    def __str__(self):
        return self.tipo;

class Moeda(models.Model):
    nome = models.TextField(blank=True)
    imagem = models.ImageField(upload_to='images/moedas/', default='')

    class Meta:
        db_table = 'moeda'

    def __str__(self):
        return self.nome;

class Pais(models.Model):
    nome = models.CharField(max_length=100, db_index= True, unique=True)
    sigla = models.CharField(max_length=5, db_index= True, unique=True)
    imagem = models.ImageField(upload_to='images/pais/', default='')
    continente = models.ForeignKey(Continente, on_delete=models.DO_NOTHING)
    moeda = models.ForeignKey(Moeda, on_delete=models.DO_NOTHING, default=1)
    populacao = models.CharField(max_length=50, default='')
    capital = models.CharField(max_length=100, default='')
    capital_sigla = models.CharField(max_length=5, default='')
    clima = models.TextField(blank=True)
    cristaos = models.TextField(blank=True)
    perseguido = models.ForeignKey(Perseguicao, on_delete=models.DO_NOTHING)
    curiosidades = models.TextField(blank=True)
    historia = models.TextField(blank=True)
    atualizado_em = models.DateField(default='')

    class Meta:
        db_table = 'pais'
        ordering = ('nome',)

    def __str__(self):
        return self.nome + " ("+self.sigla+")";

class PaisReligiao(models.Model):
    pais = models.ForeignKey(Pais, on_delete=models.DO_NOTHING)
    religiao = models.ForeignKey(Religiao, on_delete=models.DO_NOTHING)

    class Meta:
        db_table = 'pais_religiao'

class PaisIdioma(models.Model):
    pais = models.ForeignKey(Pais, on_delete=models.DO_NOTHING)
    idioma = models.ForeignKey(Idioma, on_delete=models.DO_NOTHING)

    class Meta:
        db_table = 'pais_idioma'

class Turismo(models.Model):
    nome = models.TextField(blank=True)
    descricao = models.TextField(blank=True)
    pais = models.ForeignKey(Pais, on_delete=models.DO_NOTHING)
    imagem = models.ImageField(upload_to='images/turismo/')

    class Meta:
        db_table = 'turismo'

palavra_vida/models.py
from django.db import models

# Create your models here.
from django.db import models

class Avatar(models.Model):
    imagem = models.CharField(max_length=60)

    class Meta:
        db_table = 'avatar'

    def __str__(self):
        return self.imagem;

class PalavraVida(models.Model):
    nome = models.CharField(max_length=150)
    avatar = models.ForeignKey(Avatar, on_delete=models.DO_NOTHING)
    motivacao = models.TextField()
    localidade = models.CharField(max_length=250, default='')

    class Meta:
        db_table = 'palavra_vida'

    def __str__(self):
        return self.nome;

palavra_vida/forms.py
from django import forms

from palavra_vida.models import PalavraVida

class PalavraVidaForm(forms.ModelForm):

    class Meta:
        model = PalavraVida
        fields = {'nome', 'motivacao', 'avatar', 'localidade'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['nome'].error_messages={'required': 'Campo obrigatório!'}
        self.fields['nome'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['motivacao'].error_messages = {'required': 'Campo obrigatório!'}
        self.fields['motivacao'].widget.attrs.update({'class': 'form-control form-control-sm'})

        self.fields['avatar'].error_messages = {'required': 'Campo obrigatório!'}

        self.fields['localidade'].error_messages = {'required': 'Campo obrigatório!'}
        self.fields['localidade'].widget.attrs.update({'class': 'form-control form-control-sm'})

conquista/views.py
from django.shortcuts import render

# Create your views here.
from conquista.models import Conquista

def index(request):
    linha_do_tempo = Conquista.objects.all().order_by('data')
    return render(request, 'conquista/index.html', {'linhas_do_tempo': linha_do_tempo })

missao/views.py
from django.shortcuts import render

# Create your views here.

pais/views.py
from django.shortcuts import render, get_object_or_404

from pais.models import Pais, Religiao, Idioma, Turismo, PaisIdioma, PaisReligiao


def index(request):
    lista_de_paises = Pais.objects.all().order_by('nome')
    return render(request, 'pais/index.html', {'paises': lista_de_paises})

def show(request, id):
    pais = get_object_or_404(Pais, id=id)
    religioes = PaisReligiao.objects.filter(pais_id=id)
    idiomas = PaisIdioma.objects.filter(pais_id=id)
    turismos = Turismo.objects.filter(pais_id=id)
    return render(request, 'pais/show.html', {'pais': pais, 'religioes': religioes, 'idiomas': idiomas, 'turismos': turismos})

palavra_vida/views.py
from django.shortcuts import render
from django.contrib import messages

# Create your views here.
from palavra_vida.forms import PalavraVidaForm
from palavra_vida.models import PalavraVida, Avatar

def index(request):
    palavras_vida = PalavraVida.objects.all()
    return render(request, 'palavra_vida/index.html', { 'palavras_vida': palavras_vida })

def cadastra_motivacao(request):
    avatares = Avatar.objects.all().order_by('id')
    if request.POST:
        motivacao_form = PalavraVidaForm(request.POST)

        if motivacao_form.is_valid():
            motivacao = motivacao_form.save(commit=False)
            motivacao.save()
            messages.add_message(request, messages.INFO, 'Palavra de Vida cadastrada com sucesso!')
            return render(request, 'palavra_vida/cadastra_motivacao.html', {'form': motivacao_form, 'avatares': avatares})
    else:
        motivacao_form = PalavraVidaForm()

    return render(request, 'palavra_vida/cadastra_motivacao.html', {'form': motivacao_form, 'avatares': avatares})

projeto/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

conquista/templates/conquista/index.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/conquista.css' %}" type="text/css">
{% endblock %}

{% block titulo %}
    Linha do Tempo
{% endblock %}

{% block corpo %}
<h2 class="text-center">Conquistas</h2>
<div class="row">
  <div class="container timeline-container">
    <div class="timeline">
      <ul>
        {% for item in linhas_do_tempo %}
          <li>
            <div class="timeline-content">
              <h2 class="date">{{ item.definir_mes }} de {{ item.data.year }}</h2>
              <h1>{{ item.titulo }}</h1>
              <p class="text-justify">{{ item.descricao }}</p>
              <p><strong>{{ item.localidade }}</strong></p>
              <div class="botoes">
                {% if item.link %}
                  <a href="{{ item.link }}" type="link" class="btn btn-outline-light btn-sm" target="_blank">Saiba mais</a>
                {% endif %}
                {% if item.documento %}
                  <a href="{{ item.documento.url }}" type="link" class="btn btn-light btn-sm">Veja!</a>
                {% endif %}
              </div>
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

pais/templates/pais/index.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
    Países
{% endblock %}

{% block corpo %}
<h3 class="font-weight-bold text-center">Países</h3>
<div class="row">
    {% for pais in paises %}
        <div class="col-xl-3 col-lg-3 col-6">
            <div class="card">
                <div class="card-body">
                    {% if pais.imagem %}
                        <img class="img-fluid" src="{{ pais.imagem.url }}" alt="Bandeira do país {{ pais.nome }}">
                    {% else %}
                        <div class="text md-center mb-md-8 mb-2">
                            Imagem não disponível
                        </div>
                    {% endif %}
                    <h5 class="text-center"><a class="card-title" href="{% url 'pais:show' pais.id %}">{{ pais.nome }}</a></h5>
                    <p class="card-text text-center text-justify">{{ pais.continente }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

pais/templates/pais/show.html
{% extends "base.html" %}
{% load static %}

{% block link %}
<link rel="stylesheet" href="{% static 'css/pais.css' %}" type="text/css">
{% endblock %}

{% block titulo %}
    Países
{% endblock %}

{% block corpo %}
<h3 class="font-weight-bold text-center">{{pais.nome}} ({{pais.sigla}})</h3>
<img class="img-fluid img_pais" src="{{ pais.imagem.url }}" alt="Bandeira do país {{ pais.nome }}">
<div class="form-group row">
    <div class="col-sm-3">
        <h6>Continente</h6><p> {{pais.continente}}</p>
    </div>
    <div class="col-sm-3">
        <h6>Capital</h6><p> {{pais.capital}} ({{pais.capital_sigla}})</p>
    </div>
    <div class="col-sm-3">
        <h6>População</h6><p>{{pais.populacao}}</p>
    </div>
    <div class="col-sm-3">
        <h6>Cristãos</h6><p>{{pais.cristaos}}</p>
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-6">
        <h6>Religião</h6>
        <ul>
            {% for religiao in religioes %}
                <li>
                    <a href="#" data-trigger="hover" data-toggle="tooltip" data-placement="top" data-html="true" title="{{religiao.religiao.descricao}}">
                        {{religiao.religiao.nome}}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-sm-6">
        <h6>Idioma</h6>
        <ul>
            {% for idioma in idiomas %}
                <li>{{idioma.idioma.nome}}</li>
            {% endfor %}
        </ul>
    </div>
</div>
{% if pais.perseguido_id %}
    <div class="form-group row">
        <div class="col-sm-12">
             <h6>Perseguição</h6><p class="text-justify">{{pais.perseguido.tipo}} - {{pais.perseguido.descricao}}</p>
        </div>
    </div>
{% endif %}

<div class="form-group row">
    <div class="col-sm-6">
        <h6>Clima</h6><p class="text-justify">{{pais.clima}}</p>
    </div>
    <div class="col-sm-6">
        <h6>Moeda {{pais.moeda.nome}}</h6>
        <img class="img-fluid moeda" src="{{ pais.moeda.imagem.url }}" alt="Moeda do país {{ pais.nome }}">
    </div>
</div>
<h6>Curiosidades</h6><p class="text-justify">{{pais.curiosidades}}</p>
<h6>História</h6><p class="text-justify">{{pais.historia}}</p>
<div class="form-group row">
    <div class="col-sm-12">
        <h6>Turismo</h6>
        {% for turismo in turismos %}
            <div class="col-sm-6">
                <p style="padding-left: 100px;"><strong>{{turismo.nome}}</strong></p>
                <img style="padding-right: 20px;" align="left" class="img-fluid turismo" src="{{ turismo.imagem.url }}" alt="{{ turismo.nome }}">
                <p class="text-justify" style="align: right; padding: 20px;">{{turismo.descricao}}</p>
            </div>
        {% endfor %}
    </div>
</div>

<h6>Atualizado em:</h6><p>{{pais.atualizado_em}}</p>
{% endblock %}

palavra_vida/templates/palavra_vida/cadastra_motivacao.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/palavra_vida.css' %}" type="text/css">
{% endblock %}

{% block titulo %}
    Cadastro de Palavra de Vida
{% endblock %}

{% block corpo %}
<div class="mb-4" style="padding-top: 20px;">
    <h3 class="font-weight-bold text-center">Cadastro de Palavra de Vida</h3>
</div>

<form action="" method="POST" class="pb-4" novalidate>
    <div class="row mb-xl-3">
        <div class="col-xl-12 mb-3">
            <div class="row">
                <label for="id_avatar" class="col-xl-2 font-weight-bold">Avatar</label>
                <div class="col-xl-10">
                    <div class="form-inline avatar-imagem">
                        {% for avatar in avatares %}
                            <input type="radio" id="{{ avatar.id }}" name="avatar" value="{{ avatar.id }}">
                            <label for="{{ avatar.id }}"><img src="{% static 'images/avatar/'|add:avatar.imagem %}"></label><br>
                        {% endfor %}
                    </div>
                    {% if form.avatar.errors %}
                        <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                            {% for error in form.avatar.errors %}
                                <small>{{ error }}</small>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-xl-12 mb-3">
            <div class="row">
                <label for='id_nome' class="col-xl-2 font-weight-bold">Nome</label>
                <div class="col-xl-10">
                    {{ form.nome }}
                    {% if form.nome.errors %}
                    <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                        {% for error in form.nome.errors %}
                        <small>{{ error }}</small>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-xl-12 mb-3">
            <div class="row">
                <label for="id_motivacao" class="col-xl-2 font-weight-bold">Motivação</label>
                <div class="col-xl-10">
                    {{ form.motivacao }}
                     {% if form.motivacao.errors %}
                        <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                            {% for error in form.motivacao.errors %}
                                <small>{{ error }}</small>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="col-xl-12 mb-3">
            <div class="row">
                <label for="id_localidade" class="col-xl-2 font-weight-bold">Localidade</label>
                <div class="col-xl-10">
                    {{ form.localidade }}
                     {% if form.localidade.errors %}
                        <div class="alert alert-danger mb-0" role="alert" style="padding-top: 2px; padding-bottom: 2px">
                            {% for error in form.localidade.errors %}
                                <small>{{ error }}</small>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="row mb-5">
            <div class="col-xl-6">
                <div class="row">
                    <div class="col-xl-10 offset-xl-2">
                        {% csrf_token %}
                        <button id="botao" type="submit" class="btn btn-primary">
                            Cadastrar
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

palavra_vida/templates/palavra_vida/index.html
{% extends "base.html" %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/palavra_vida.css' %}" type="text/css">
{% endblock %}

{% block titulo %}
    Palavras de Vida
{% endblock %}

{% block corpo %}
<a role="button" class="btn btn-primary insert" href="{% url 'palavra_vida:cadastra_motivacao' %}">Inserir Motivação</a>
<h3 class="font-weight-bold text-center">Palavras de Vida</h3>

<div class="container">
    <section id="motivacao-container">
        <div id="carousel-motivacao" class="carousel slide wrapper" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-id" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-id" data-slide-to="1"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    {% for palavra_vida in palavras_vida %}
                        <div class="motivacao-box">
                            <p class="motivacao-msg">{{ palavra_vida.motivacao }}</p>
                            <img src="{% static 'images/avatar/'|add:palavra_vida.avatar.imagem %}">
                            <p class="motivacao-name font-weight-bold">{{ palavra_vida.nome }}</p>
                            <p class="motivacao-localidade">{{ palavra_vida.localidade }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
</div>

<script src="https://apps.elfsight.com/p/platform.js" defer></script>
<div class="elfsight-app-ec74ce28-d36a-48eb-b599-c4ae7eed6ea8"></div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block titulo %}
            Allana Oliveira
        {% endblock %}
    </title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/all.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/template.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="shortcut icon" href="{% static 'images/favicon.jpg' %}" />

    {% block link %}

    {% endblock %}

    <link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'>

    <script src="{% static 'js/jquery-3.5.1.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/template.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-light bg-light navbar-expand-md fixed-top cabecalho">
        <a class="nav-link nav-item d-flex justify-content-center" href="{% url 'index' %}"><i class="fas fa-door-open"></i></a>

        <div class="navbar-nav mr-auto esquerda d-none d-md-block">
            <a class="d-none d-md-block nav-link nav-item" href="https://wa.me/5521996667273" target="_blank"><i class="far fa-comments"></i> Entre em contato!</a>
        </div>
        <div class="navbar-nav esquerda mr-auto d-block d-md-none">
            <a class="d-block d-md-none nav-link nav-item" href="https://wa.me/5521996667273" target="_blank"><i class="far fa-comments fa-2x"></i></a>
        </div>

        <div class="navbar-nav mr-auto direita">
            <div class="row">
                <a class="nav-link nav-item d-flex justify-content-center small mr-2" href="https://www.instagram.com/oliveira_allana/" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
                <a class="nav-link nav-item d-flex justify-content-center small mr-2" href="https://www.facebook.com/Allana.C.deoliveira" target="_blank"><i class="fab fa-facebook fa-2x"></i></a>
                <a class="nav-link nav-item d-flex justify-content-center small mr-2" href="https://www.youtube.com/user/AllaanaGodislove" target="_blank"><i class="fab fa-youtube fa-2x"></i></a>
            </div>
        </div>

        <div class="navbar-nav">
            <a class="d-none d-md-block nav-link nav-item hastag" href="{% url 'palavra_vida:index' %}"><i class="fas fa-hashtag"></i><span>juntospelomundo</span></a>
        </div>
    </nav>

    <main class="principal">
        {% block corpo %}

        {% endblock %}
    </main>

    <footer class="rodape">
        <div class="text-center py-3">
            <p>Allana Capistrano de Oliveira</p>
            <p>CPF: 148.264.797-43</p>
        </div>
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <p>Banco do Brasil</p>
                    <p>Agência: 0000</p>
                    <p>Conta</p>
                </div>
                <div class="col text-center">
                    <p>Banco Itaú</p>
                    <p>Agência: 0000</p>
                    <p>Conta</p>
                </div>
            </div>
        </div>
        <hr style="border-color: #7bac3b;">
        <div class="footer-copyright text-center py-3">
          <p><i class="far fa-copyright"></i> Allana Capistrano de Oliveira 2020</p>
          <p><i class="fas fa-globe-americas"></i> Todos os direitos reservados</p>
        </div>
    </footer>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block corpo %}
  <img src="{% static 'images/allana.png' %}" class="img-fluid nome" alt="Foto da Allana Oliveira dentro de um círculo e ao lado direito o nome Allana Oliveira">
  <p class="container apresentacao text-justify">Sejam bem-vind@s ao meu portfólio! Aqui você irá conhecer um pouquinho mais sobre mim e o que enche meu coração de alegria. Fique a vontade!</p>
  <div class="menus">
    <a href="{% url 'pais:index' %}"><img src="{% static 'images/mundo.gif' %}" class="img-fluid mundo" alt="Mundo girando - Link para projetos sobre países"></a>
    <div class="ciencia_da_computacao">
      <div class="img_computacao">
        <img class="img-fluid" src="{% static 'images/computador.png' %}" alt="Computador com uma lâmpada saindo dele">
      </div>
      <div class="text_menu computacao">
        <p class="text-justify">Sou formada em Ciência da Computação pela Universidade Federal Fluminense (2016-2020) e apaixonada por Design que deu início ao projeto da Shine Design.
          <a href="{% url 'conquista:index' %}" type="link" class="btn btn-light btn-sm">Saiba mais</a>
        </p>
      </div>
    </div>
    <div class="missoes">
      <div class="img_mapa">
        <img class="img-fluid" src="{% static 'images/mapa.png' %}" alt="Um mapa com um pin soltando dele">
      </div>
      <div class="text_menu missao">
        <p class="text-justify">Possuo um amor maior que eu por almas e por isso decidi viver a missão de Deus para a minha vida.
          <button type="link" class="btn btn-light btn-sm">Saiba mais</button>
        </p>
      </div>
    </div>
  </div>
{% endblock %}